export const values = {
  adult: false,
  backdrop_path: "",
  genre_ids: [0],
  genres:[{id:0,name:""}],
  production_countries:[{name:""}],
  production_companies:[{logo_path:"",name:""}],
  id: 0,
  original_language: "",
  original_title: "",
  overview: "",
  popularity: 0,
  poster_path: "",
  release_date: "",
  title: "",
  video: false,
  vote_average: 0,
  vote_count: 0,
};
